--------------------------------------------
-- EasyUI API
--------------------------------------------
CreateAddon = EasyUI["CreateAddon"]
CreateFrame = EasyUI["CreateFrame"]
CreateWindow = EasyUI["CreateWindow"]
CreatePageSet = EasyUI["CreatePageSet"]
CreateButton = EasyUI["CreateButton"]
CreateEdit = EasyUI["CreateEdit"]
CreateCheckBox = EasyUI["CreateCheckBox"]
CreateComboBox = EasyUI["CreateComboBox"]
CreateRadioBox = EasyUI["CreateRadioBox"]
CreateCSlider = EasyUI["CreateCSlider"]
CreateColorBox = EasyUI["CreateColorBox"]
CreateScroll = EasyUI["CreateScroll"]
CreateUICheckBox = EasyUI["CreateUICheckBox"]
CreateHandle = EasyUI["CreateHandle"]
CreateText = EasyUI["CreateText"]
CreateImage = EasyUI["CreateImage"]
CreateAnimate = EasyUI["CreateAnimate"]
CreateShadow = EasyUI["CreateShadow"]
CreateBox = EasyUI["CreateBox"]
CreateTreeLeaf = EasyUI["CreateTreeLeaf"]
